# Generated by Django 5.0.4 on 2024-05-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_owner'),
    ]

    operations = [
    ]
