# Generated by Django 5.0.4 on 2024-05-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20240504_0049'),
    ]

    operations = [
    ]
